import {CardType} from '../../types';
import { CARD_CONFIG } from './cardConfig';

type RowConfig = Record<
  CardType,
  {
    ITEM_COUNT: number;
    HEIGHT: number;
    WIDTH: number;
    API_PAGE_SIZE: number;
  }
>;

export const ROW_CONFIG: RowConfig = {
  HERO: {
    ITEM_COUNT: 50,
    API_PAGE_SIZE: 10,
    HEIGHT:
      CARD_CONFIG.HERO.CARD.HEIGHT +
      CARD_CONFIG.HERO.TITLE.HEIGHT +
      CARD_CONFIG.HERO.ROW_GAP,
    WIDTH: CARD_CONFIG.HERO.CARD.WIDTH + CARD_CONFIG.HERO.CARD.GAP,
  },
  VERTICAL: {
    ITEM_COUNT: 80,
    API_PAGE_SIZE: 15,
    HEIGHT:
      CARD_CONFIG.VERTICAL.CARD.HEIGHT +
      CARD_CONFIG.VERTICAL.TITLE.HEIGHT +
      CARD_CONFIG.VERTICAL.ROW_GAP,
    WIDTH: CARD_CONFIG.VERTICAL.CARD.WIDTH + CARD_CONFIG.VERTICAL.CARD.GAP,
  },
  REGULAR: {
    ITEM_COUNT: 40,
    API_PAGE_SIZE: 15,
    HEIGHT:
      CARD_CONFIG.REGULAR.CARD.HEIGHT +
      CARD_CONFIG.REGULAR.TITLE.HEIGHT +
      CARD_CONFIG.REGULAR.ROW_GAP,
    WIDTH: CARD_CONFIG.REGULAR.CARD.WIDTH + CARD_CONFIG.REGULAR.CARD.GAP,
  },
};
